"""db Model for 'other' items

Revision ID: 1ac4a21accba
Revises: 60942490db8b
Create Date: 2020-04-14 10:18:54.876169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac4a21accba'
down_revision = '60942490db8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothingItem', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other')
    # ### end Alembic commands ###
