"""new primary clothing table

Revision ID: 60942490db8b
Revises: d05b0c518e87
Create Date: 2020-04-13 11:07:53.229201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60942490db8b'
down_revision = 'd05b0c518e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primary_clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothingItem', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('primary_clothes')
    # ### end Alembic commands ###
