"""correct Col names

Revision ID: 6a51349168b4
Revises: fe004e1f2f69
Create Date: 2020-04-13 10:47:58.485893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a51349168b4'
down_revision = 'fe004e1f2f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prim_clothes', sa.Column('ClothingPiece', sa.String(length=64), nullable=True))
    op.add_column('prim_clothes', sa.Column('Quantity', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prim_clothes_ClothingPiece'), 'prim_clothes', ['ClothingPiece'], unique=True)
    op.drop_index('ix_prim_clothes_name', table_name='prim_clothes')
    op.drop_column('prim_clothes', 'name')
    op.drop_column('prim_clothes', 'short_pants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prim_clothes', sa.Column('short_pants', sa.INTEGER(), nullable=True))
    op.add_column('prim_clothes', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_prim_clothes_name', 'prim_clothes', ['name'], unique=1)
    op.drop_index(op.f('ix_prim_clothes_ClothingPiece'), table_name='prim_clothes')
    op.drop_column('prim_clothes', 'Quantity')
    op.drop_column('prim_clothes', 'ClothingPiece')
    # ### end Alembic commands ###
