"""changed name for convenience

Revision ID: b50120d65fed
Revises: 1ac4a21accba
Create Date: 2020-04-14 10:45:14.034892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50120d65fed'
down_revision = '1ac4a21accba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothingItem', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('other')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clothingItem', sa.VARCHAR(length=64), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('other_clothes')
    # ### end Alembic commands ###
