"""correct Col names

Revision ID: d05b0c518e87
Revises: 6a51349168b4
Create Date: 2020-04-13 10:54:22.502544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05b0c518e87'
down_revision = '6a51349168b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prim_clothes', sa.Column('Clothing', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_prim_clothes_Clothing'), 'prim_clothes', ['Clothing'], unique=True)
    op.drop_index('ix_prim_clothes_ClothingPiece', table_name='prim_clothes')
    op.drop_column('prim_clothes', 'ClothingPiece')
    op.drop_column('prim_clothes', 'name')
    op.drop_column('prim_clothes', 'short_pants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prim_clothes', sa.Column('short_pants', sa.INTEGER(), nullable=True))
    op.add_column('prim_clothes', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('prim_clothes', sa.Column('ClothingPiece', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_prim_clothes_ClothingPiece', 'prim_clothes', ['ClothingPiece'], unique=1)
    op.drop_index(op.f('ix_prim_clothes_Clothing'), table_name='prim_clothes')
    op.drop_column('prim_clothes', 'Clothing')
    # ### end Alembic commands ###
