"""highschool clothes db model

Revision ID: dced5f16f09c
Revises: b50120d65fed
Create Date: 2020-04-14 13:48:18.710640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dced5f16f09c'
down_revision = 'b50120d65fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothingItem', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('high_clothes')
    # ### end Alembic commands ###
