"""primary school clothes

Revision ID: fe004e1f2f69
Revises: f11964854f0e
Create Date: 2020-04-13 10:34:02.830144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe004e1f2f69'
down_revision = 'f11964854f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prim_clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('short_pants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prim_clothes_name'), 'prim_clothes', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prim_clothes_name'), table_name='prim_clothes')
    op.drop_table('prim_clothes')
    # ### end Alembic commands ###
